### ISSUE TITLE
php7.0无法运行

### ISSUE THREAD

**Issue by kalsolio** [vueadmin/vue-admin#1]
Problem 1
    - Installation request for doctrine/cache v1.7.1 -> satisfiable by doctrine/cache[v1.7.1].
    - doctrine/cache v1.7.1 requires php ~7.1 -> your PHP version (7.0.27) does not satisfy that requirement.

**Comment by vueadmin** [comment]
其实建议使用前后端分离

**Comment by vueadmin** [comment]
不过我还是会检查一下的

**Comment by vueadmin** [comment]
只支持7.1
